{"PlusMinus": "24", "pim": "26", "gp": "75", "points": "96", "rank": "1", "assists": "58", "goals": "38", "position": "F", "name": "Connor McDavid"}
{"PlusMinus": "18", "pim": "40", "gp": "73", "points": "95", "rank": "2", "assists": "58", "goals": "37", "position": "F", "name": "Nikita Kucherov"}
{"PlusMinus": "15", "pim": "53", "gp": "67", "points": "92", "rank": "3", "assists": "54", "goals": "38", "position": "F", "name": "Nathan MacKinnon"}
{"PlusMinus": "16", "pim": "69", "gp": "71", "points": "91", "rank": "4", "assists": "50", "goals": "41", "position": "F", "name": "Evgeni Malkin"}
{"PlusMinus": "18", "pim": "20", "gp": "75", "points": "90", "rank": "5", "assists": "64", "goals": "26", "position": "F", "name": "Claude Giroux"}
{"PlusMinus": "18", "pim": "18", "gp": "76", "points": "86", "rank": "6", "assists": "53", "goals": "33", "position": "F", "name": "Anze Kopitar"}
{"PlusMinus": "22", "pim": "53", "gp": "75", "points": "86", "rank": "7", "assists": "59", "goals": "27", "position": "F", "name": "Steven Stamkos"}
{"PlusMinus": "-1", "pim": "36", "gp": "75", "points": "83", "rank": "8", "assists": "53", "goals": "30", "position": "F", "name": "Phil Kessel"}
{"PlusMinus": "8", "pim": "44", "gp": "74", "points": "83", "rank": "9", "assists": "64", "goals": "19", "position": "F", "name": "Blake Wheeler"}
{"PlusMinus": "11", "pim": "34", "gp": "70", "points": "82", "rank": "10", "assists": "49", "goals": "33", "position": "F", "name": "Taylor Hall"}
{"PlusMinus": "0", "pim": "26", "gp": "76", "points": "82", "rank": "11", "assists": "59", "goals": "23", "position": "F", "name": "Johnny Gaudreau"}
{"PlusMinus": "4", "pim": "28", "gp": "74", "points": "81", "rank": "12", "assists": "37", "goals": "44", "position": "F", "name": "Alexander Ovechkin"}
{"PlusMinus": "-1", "pim": "46", "gp": "75", "points": "81", "rank": "13", "assists": "56", "goals": "25", "position": "F", "name": "Sidney Crosby"}
{"PlusMinus": "6", "pim": "32", "gp": "74", "points": "80", "rank": "14", "assists": "53", "goals": "27", "position": "F", "name": "Mikko Rantanen"}
{"PlusMinus": "8", "pim": "42", "gp": "75", "points": "80", "rank": "15", "assists": "61", "goals": "19", "position": "F", "name": "Jakub Vor\u00e1cek"}
{"PlusMinus": "-8", "pim": "24", "gp": "75", "points": "78", "rank": "16", "assists": "45", "goals": "33", "position": "F", "name": "John Tavares"}
{"PlusMinus": "32", "pim": "55", "gp": "59", "points": "78", "rank": "17", "assists": "46", "goals": "32", "position": "F", "name": "Brad Marchand"}
{"PlusMinus": "0", "pim": "26", "gp": "75", "points": "76", "rank": "18", "assists": "56", "goals": "20", "position": "F", "name": "Mathew Barzal"}
{"PlusMinus": "4", "pim": "14", "gp": "72", "points": "74", "rank": "19", "assists": "48", "goals": "26", "position": "F", "name": "Aleksander Barkov"}
{"PlusMinus": "12", "pim": "36", "gp": "74", "points": "72", "rank": "20", "assists": "33", "goals": "39", "position": "F", "name": "Eric Staal"}
{"PlusMinus": "16", "pim": "28", "gp": "73", "points": "72", "rank": "21", "assists": "43", "goals": "29", "position": "F", "name": "David Pastrnak"}
{"PlusMinus": "-15", "pim": "30", "gp": "76", "points": "72", "rank": "22", "assists": "46", "goals": "26", "position": "F", "name": "Patrick Kane"}
{"PlusMinus": "7", "pim": "37", "gp": "75", "points": "71", "rank": "23", "assists": "32", "goals": "39", "position": "F", "name": "Tyler Seguin"}
{"PlusMinus": "2", "pim": "46", "gp": "71", "points": "71", "rank": "24", "assists": "50", "goals": "21", "position": "F", "name": "Evgeny Kuznetsov"}
{"PlusMinus": "26", "pim": "25", "gp": "75", "points": "70", "rank": "25", "assists": "40", "goals": "30", "position": "F", "name": "Sean Couturier"}
{"PlusMinus": "-7", "pim": "50", "gp": "73", "points": "69", "rank": "26", "assists": "39", "goals": "30", "position": "F", "name": "Vincent Trocheck"}
{"PlusMinus": "14", "pim": "50", "gp": "75", "points": "69", "rank": "27", "assists": "41", "goals": "28", "position": "F", "name": "Jamie Benn"}
{"PlusMinus": "18", "pim": "26", "gp": "76", "points": "69", "rank": "28", "assists": "44", "goals": "25", "position": "F", "name": "Artemi Panarin"}
{"PlusMinus": "34", "pim": "40", "gp": "72", "points": "69", "rank": "29", "assists": "45", "goals": "24", "position": "F", "name": "Jonathan Marchessault"}
{"PlusMinus": "-17", "pim": "17", "gp": "71", "points": "69", "rank": "30", "assists": "51", "goals": "18", "position": "F", "name": "Joshua Bailey"}
{"PlusMinus": "9", "pim": "22", "gp": "74", "points": "68", "rank": "31", "assists": "25", "goals": "43", "position": "F", "name": "Patrik Laine"}
{"PlusMinus": "41", "pim": "12", "gp": "75", "points": "66", "rank": "32", "assists": "27", "goals": "39", "position": "F", "name": "William Karlsson"}
{"PlusMinus": "5", "pim": "28", "gp": "71", "points": "66", "rank": "33", "assists": "43", "goals": "23", "position": "F", "name": "Leon Draisaitl"}
{"PlusMinus": "0", "pim": "48", "gp": "69", "points": "66", "rank": "34", "assists": "50", "goals": "16", "position": "F", "name": "David Perron"}
{"PlusMinus": "-2", "pim": "66", "gp": "75", "points": "65", "rank": "35", "assists": "39", "goals": "26", "position": "F", "name": "Alexander Radulov"}
{"PlusMinus": "1", "pim": "28", "gp": "73", "points": "65", "rank": "36", "assists": "42", "goals": "23", "position": "F", "name": "Jonathan Huberdeau"}
{"PlusMinus": "3", "pim": "24", "gp": "74", "points": "64", "rank": "37", "assists": "33", "goals": "31", "position": "F", "name": "Sean Monahan"}
{"PlusMinus": "-4", "pim": "20", "gp": "75", "points": "64", "rank": "38", "assists": "44", "goals": "20", "position": "F", "name": "Mitchell Marner"}
{"PlusMinus": "5", "pim": "14", "gp": "70", "points": "63", "rank": "39", "assists": "32", "goals": "31", "position": "F", "name": "Rickard Rakell"}
{"PlusMinus": "18", "pim": "56", "gp": "75", "points": "63", "rank": "40", "assists": "38", "goals": "25", "position": "F", "name": "Brayden Schenn"}
{"PlusMinus": "21", "pim": "22", "gp": "75", "points": "62", "rank": "41", "assists": "34", "goals": "28", "position": "F", "name": "Brayden Point"}
{"PlusMinus": "5", "pim": "24", "gp": "71", "points": "62", "rank": "42", "assists": "36", "goals": "26", "position": "F", "name": "Sebastian Aho"}
{"PlusMinus": "9", "pim": "10", "gp": "58", "points": "62", "rank": "43", "assists": "42", "goals": "20", "position": "F", "name": "Mark Stone"}
{"PlusMinus": "9", "pim": "14", "gp": "75", "points": "61", "rank": "44", "assists": "38", "goals": "23", "position": "F", "name": "Teuvo Ter\u00e4v\u00e4inen"}
{"PlusMinus": "-5", "pim": "30", "gp": "74", "points": "61", "rank": "45", "assists": "46", "goals": "15", "position": "D", "name": "John Carlson"}
{"PlusMinus": "6", "pim": "22", "gp": "75", "points": "61", "rank": "46", "assists": "54", "goals": "7", "position": "D", "name": "John Klingberg"}
{"PlusMinus": "15", "pim": "17", "gp": "73", "points": "60", "rank": "47", "assists": "31", "goals": "29", "position": "F", "name": "Vladimir Tarasenko"}
{"PlusMinus": "32", "pim": "22", "gp": "66", "points": "60", "rank": "48", "assists": "38", "goals": "22", "position": "F", "name": "Reilly Smith"}
{"PlusMinus": "0", "pim": "37", "gp": "75", "points": "60", "rank": "49", "assists": "41", "goals": "19", "position": "F", "name": "Joe Pavelski"}
{"PlusMinus": "-15", "pim": "40", "gp": "75", "points": "60", "rank": "50", "assists": "49", "goals": "11", "position": "D", "name": "Brent Burns"}
